baseURL = 'https://www.ulynks.io/'
languageCode = 'en-us'
title = 'uLynks'
# theme = 'ananke'
theme = 'ulynks'

[params]
  subtitle = ''
  umami = '3cf42fbf-5ff7-4ba7-b4d1-607641c5b4e8'
  [params.contact]
    email = 'contact@ulynks.io'
    phone = ''

[[menus.main]]
name = 'Home'
pre = "home"
url = "/"
weight = 1

[[menus.main]]
name = 'About us'
pageRef = '/about-us'
weight = 2

[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 3

[[menus.main]]
name = 'Products'
pageRef = '/products'
weight = 4

[[menus.main]]
name = 'Contact us'
pageRef = '/contact-us'
weight = 5

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
